name: Deploy to Server

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Deploying to server..."
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP 'mkdir -p /files/public_html/'
          sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -r ./* $USERNAME@$SERVER_IP:/files/public_html/
