name: Deploy to FTP Server

on:
  push:
    branches:
      - master  # تغییر به شاخه‌ای که می‌خواهید از آن deploy کنید

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"  # مسیر پوشه‌ای که می‌خواهید دیپلوی کنید
          server-dir: "/public_html/menutest/"  # مسیر پوشه مقصد در هاست
